# Generated by Django 2.0.4 on 2018-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('habits', models.TextField()),
                ('sex', models.BooleanField()),
            ],
        ),
    ]
